---
title: "Geospatial with R"
linktitle: "14: Shrinkage with LASSO and Ridge"
read_date: "2022-04-27"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
---

## Required Reading

- This page.

### Guiding Questions

- What is *shrinkage*?
- What do we do with too may right-hand-side variables?
- What is LASSO?

# This week is a little different
We will use the lecture slides from my friend and ace economist, Ed Rubin (U of Oregon). They are available [right here](htts://raw.githack.com/edrubin/EC524W20/master/lecture/005/005-slides.html#1). A couple things first, though:

## The data and packages

Dr. Rubin uses the `ISLR` package's `credit` dataset, which is similar to one we've used before:

```{r credit-data, echo = T}
library(ISLR)
credit = ISLR::Credit
head(credit)

```

We will also need to load the `caret` package (which you're used before), as well as the `glmnet` package, which is new for us.

Now, back to the [lecture notes for today]](htts://raw.githack.com/edrubin/EC524W20/master/lecture/005/005-slides.html#1)





# Lecture Video
The lecture video for this material is [available here <i class="fas fa-film"></i>]()