---
title: Readings, lectures, and videos
menu:
  content:
    parent: Overview
    weight: 1
type: docs
weight: 1
date: "2020-09-01"
---

Each week has a set of required readings that you should complete ***before*** watching the lecture. If you are attending in-person on Tuesdays, you should complete the reading, attend class, then watch the lecture and do the associated content on Thursday. If you are attending on Thursdays, you should read first, watch the lecture, then attend the lecture. Both groups will be working on the last part of the labs between Thursday afternoon and Monday at 11:59 PM (when the labs are due).

The course content is structured as follows. For each topic, we begin with a set of questions that might guide your reading and help frame your thoughts. These questions can serve as helpful starting places for your  You should not try to respond to all of these (or any of them if you don't want to)—they'll just help you know what to look for and think about as you read.

Every weekly session also has some collection of YouTube videos (generally fairly short) that are associated with each week. These lectures are inherently different from the written content, and you should consider them as high-level overviews of the written content. I am not replicating the written text as-is and (especially if you're struggling) you should engage with lectures and written materials in equal measure. The lecture slides are HTML files made with the `R` package [**`xaringan`**](https://bookdown.org/yihui/rmarkdown/xaringan.html). For each of the weekly pages, you will see buttons for opening the presentation in a new tab.^[I aspire to include a link for downloading a PDF of the slides in case you want to print them or store them on your computer. However, this seems... ambitious. As of right now, I have not finished this.].

<p style="text-align:center;"><span class="btn btn-primary btn-lg"><i class="fas fa-external-link-alt"></i> View all slides in new window</span>

The slides are also embedded on each page. You can click in the slides and navigate through them with <kbd>←</kbd> and <kbd>→</kbd>. If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while viewing the slides you can see a list of slide-specific commands (like <kbd>f</kbd> for fullscreen or <kbd>p</kbd> for presenter mode if you want to see my notes).
