[build]
command = "hugo"
publish = "public"
[context.production.environment]
  HUGO_VERSION = "0.99.1"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL"
