---
title: "(Re)Introduction to R"
linktitle: "0: (Re)Introduction to R"
date: "2020-05-11"
class_date: "2020-05-11"
output:
  blogdown::html_page:
    toc: true
menu:
  example:
    parent: Examples
    weight: 1
type: docs
weight: 1
editor_options:
  chunk_output_type: console
---

```{r write-data, include=FALSE}
readr::write_csv(gapminder::gapminder, here::here("static", "data", "gapminder.csv"))
```

# Introduction to Examples

Examples in this class are designed to be presented in-class. Accordingly, the notes here are *not* comprehensive. Instead, they are intended to guide students through

I'm also aware that my writing is dry and lifeless. If you're reading this online without the advantage of seeing it in person, don't worry---I'll be "funnier" in class.^[Comments from previous classes indicate that I am not, in fact, funny.]

## Basic process for working with RStudio

For this example, we are going to create a new RStudio project, download some data, put the data in the project, and make a graph of it using R Markdown. You'll follow this same process any time you start a new project or exercise. You will need to tackle this in class and there are some specific exercises and reflections for each class.

To follow along, download this CSV file here (you may need to right click on it and select "Save As…"):

- [<i class="fas fa-file-csv"></i> `gapminder.csv`](/data/gapminder.csv)

### Reading in Data

Our first step in any data project is actually reading in data.
