---
title: "Data Wrangling"
linktitle: "12: Data Wrangling"
output:
  blogdown::html_page:
    toc: true
menu:
  example:
    parent: Examples
    weight: 2
type: docs
weight: 1
editor_options:
  chunk_output_type: console
---


# Data to be wrangled

You work for a travel booking website as a data analyst. A hotel has asked your company for data on corporate bookings at the hotel via your site. Specifically, they have five corporations that are frequent customers of the hotel, and they want to know who spends the most with them. They've asked you to help out. Most of the corporate spending is in the form of room reservations, but there are also parking fees that the hotel wants included in the analysis. Your goal: total up spending by corporation and report the biggest and smallest spenders inclusive of rooms and parking.

Unfortunately, you only have the following data:

- [<i class="fas fa-file-csv"></i> `booking.csv`](/data/Example11_booking.csv) - Contains the corporation name, the room type, and the dates someone from the corporation stayed at the hoted.

- [<i class="fas fa-file-csv"></i> `roomrates.csv`](/data/Example11_roomrates.csv) - Contains the price of each room on each day

- [<i class="fas fa-file-csv"></i> `parking.csv`](/data/Example11_parking.csv) - Contains the corporations who negotiated free parking for employees

- Parking at the hotel is \$60 if you don't have free parking. This hotel is in California, so everyone drives and parks when they stay.



:::fyi

Some tips:

- Right-click on each of the links, copy the address, and read the URL in using `read.csv` or `read_csv` or whatever you prefer to read .csv's

- You'll find you need to use most of the tools we covered on Tuesday including `gather`, `separate` and more.

:::


```{r eval = F, include=F}

booking_raw = read_csv('http://localhost:4321/data/Example11_booking.csv')
roomrates_raw = read_csv('http://localhost:4321/data/Example11_roomrates.csv')
parking_raw = read_csv('http://localhost:4321/data/Example11_parking.csv')

# booking_raw = read_csv('https://ssc442kirkpatrick.netlify.app/data/Example11_booking.csv')
# roomrates_raw = read_csv('https://ssc442kirkpatrick.netlify.app/data/Example11_roomrates.csv')
# parking_raw = read_csv('https://ssc442kirkpatrick.netlify.app/data/Example11_parking.csv')


## gather roomrates to merge to booking ##
roomrates = gather(roomrates_raw, convert = T) %>% # this might be tricky since it doesn't require any options!
  separate(key, sep = '_', into = c('price','roomtype','date')) %>%
  dplyr::mutate(date_occupied = ymd(date)) %>%      # NOTE: new column name is exactly the column name for date in booking
  dplyr::select(date_occupied, roomtype, rate = value)   # NOTE: column name can be renamed on the fly with select

## Merge booking to parking
booking = booking_raw %>%
  left_join(parking_raw, by = 'corp') %>%
  dplyr::mutate(Parking = case_when(
    FreeParking==T ~ 0,
    is.na(FreeParking) ~ 60,   # Parking is now $ spent on parking
    TRUE ~ as.numeric(NA)))

booking.m = booking %>%
  separate(room_use, sep = '_', into = 'roomtype', extra = 'drop')  # NOTE: new name for room_use corresponds to the name in roomrates

setequal(booking.m$roomtype, roomrates$roomtype)

booking.m = booking.m %>%
  left_join(roomrates, by = c('date_occupied','roomtype'))

booking.summary = booking.m %>%
  group_by(corp) %>%
  dplyr::summarize(sumSpent = sum(rate))

booking.summary
# B with 98,318
```
