---
title: Practical Content
menu:
  example:
    weight: 1
type: docs
weight: 1
---

This section contains the content covered in Thursday lectures and some annotated `R` code that you can use as a reference for creating your own work. The intention is that in the Content section, you will sequentially build up your understanding of `R` and data analytics; here, you can see how all the pieces work together.

Visit this section after you have finished the readings in the Content section and any supplemental lecture videos.

Many of the examples also contain videos of me live-coding so you can see what it looks like to work with `R` in real time.^[I might edit these videos for length and because I like to talk to myself when I'm programming. Also, too much swearing.] Hopefully, you'll find it useful to watch the practice of coding. You'll also notice me make all sorts of errors. This is normal. If you're finding yourself making lots of errors and generally struggling to get your code to run, start by working with the final code and reverse-engineer the solution you want.
