---
title: "Schedule"
slug: schedule
---

Below is a roadmap for the semester. Note that this will inevitably change from the first day you access this course. However, whatever is listed below should be considered canon.

As mentioned in the syllabus, the course is structured by each week. Every week has three important sections.

### A/B Structure

The class is structured by dividing the student roster into two subsets, forming an "A" group and a "B" group. Your assigned group dictates what time you work on the "in-class" work. In these classes, we will have a short, practical lecture and an activity which is designed to give you hands-on experience and give you a greater understanding of the broader material. The class is split to help enable (at least some) interaction with each other and the Instructor. Out of class, you will complete readings and can watch (short) recorded lectures on the week's topic. Note, though, that you are not required to view supplemental recorded videos. Finally, we note that the fact you are doing something on Thursday morning rather than Thursday afternoon (or vice versa) will not hurt you.^[You may switch from the A to the B group (or vice versa) with notice to the TA via email. You may only do this once over the semester.]

- [**Content**](/content/) (<i class="fas fa-book-reader"></i>): This page contains the readings and recorded lectures for the topic. These pages should be read completely. Lectures are *not* an exact replication of the written content. On the contrary, the lectures are intended to keep you focused on the high-level ideas, while the readings are broader and more comprehensive. Accordingly, lectures are shorter than the (often quite lengthy) written content.

- [**Example**](/example/) (<i class="fas fa-laptop-code"></i>): This page contains `R` code that we will discuss in Thursday classes. In addition to teaching specific content, these examples are intended as a useful reference to various functions that you will need on (nearly) weekly labs and in your group project.

- [**Labs**](/assignment/) (<i class="fas fa-pencil-ruler"></i>): This page contains the instructions for either the Lab (1–3 brief tasks), or for the two mini projects and final project. **Assignments are due by 11:59 PM (Eastern) on the Monday after they're posted.**

### Lab Hours (TA)

The teaching assistant for this course (Anh Do; doanh@msu.edu) will host a (very short) supplemental lecture each week to help promote additional understanding. This will be followed by (or preceeded by) open Q&A about the week's content. I highly encourage you to utilize this resource, especially if you struggle with basic `R` programming.


:::note
**tl;dr**: You should follow this general process (in order) each week:

- Do everything on the content (<i class="fas fa-book-reader"></i>) page
- Come to the lecture on Tuesday and come to your assigned time on Thursday.
- While "in class", work through the example (<i class="fas fa-laptop-code"></i>) page
- Complete the lab (<i class="fas fa-pencil-ruler"></i>) before the next week.
- As needed,
:::

---

`r blogdown::shortcode("schedule")`
