---
title: "Final project"
date: "2020-12-17"
due_date: "2020-12-17"
due_time: "11:59 PM"
output:
  blogdown::html_page:
    toc: true
menu:
  assignment:
    parent: Projects
    weight: 1
type: docs
editor_options:
  chunk_output_type: console
---

## Requirements

Data analytics is inherently a hands-on endeavor. Accordingly, the final project for this class is hands-on. As per the overview page, the final project has the following elements:

1. For your final project in this class, you will analyze **existing data** in some area of interest to you.[^3] Aggregating data from multiple sources is encouraged, but is not required.

[^3]: Note that **existing** is taken to mean that you are not permitted to collect data by interacting with other people. That is not to say that you cannot gather data that previously has not been gathered into a single place---this sort of exercise is encouraged. But you cannot stand with a clipboard outside a store and count visitors (for instance).

2. You must visualize (at least) three **interesting** features of that data. Visualizations should aid the reader in understanding something about the data that might not be readily aparent.[^4]

3. You must come up with some analysis---using tools from the course---which relates your data to either a prediction or a policy conclusion. For example, if you collected data from Major League Baseball games, you could try to "predict" whether a left-hander was pitching based solely on the outcomes of the batsmen.

4. You will submit **three things** via D2L:

- A PDF of your report (see the outline below for details of what this needs to contain). You should compile this with R Markdown. You might want to write the prose-heavy sections in a word processor like Word or Google Docs and copy/paste the text into your `R` Markdown document, since RStudio doesn't have a nice spell checker or grammar checker. This should have *no visible `R` code, warnings, or messages in it*.  To do this, you must set `echo = FALSE` at the beginning of your document before you knit.
- The same PDF as above, but with all the R code in it (set `echo = TRUE` at the beginning of your document and reknit the file). Please label files in an obvious way.
- A CSV file of your data; or a link to the data online if your code pulls from the internet. This must be a separate file titled "data.csv" or "data.txt" as applicable.

This project is due by **7:00 PM on Monday, December 14, 2020.** <span style="color: #81056F; font-weight: bold"> No late work will be accepted.</span>

You can either run the analysis in RStudio locally on your computer (highly recommended!), since you won't have to worry about keeping all your work on RStudio's servers), or use an RStudio.cloud project.

**There is no final exam. This project is your final exam.**

The project will ***not*** be graded using a check system, and will be graded by me (the main instructor, not a TA). I will evaluate the following four elements of your project:

1. Technical skills: Was the project easy? Does it showcase mastery of data analysis?
2. Visual design: Was the information smartly conveyed and usable? Was it beautiful?
3. Analytic design: Was the analysis appropriate? Was it sensible, given the dataset?
4. Story: Did we learn something?
5. Following instructions: Did you surpress `R` code as asked? Did you submit a separate datafile and label it correctly?

If you've engaged with the course content and completed the exercises and mini projects throughout the course, you should do just fine with the final project.


## Teams

Most importantly, **you must work with classmates**. You will work in groups of four people on your project. (There may be some groups of three). Your team must come up with a name and a **Github** site for your project and labs. Your team will earn the same scores on all projects. To combat additional freeloading, we will use a reporting system. Any team member can email me to report another team member's lack of participation secretly. See below for details. Two strikes will result in a 25% grade deduction on the mini projects and final project; three strikes will result in a 50% deduction.

Here's how we will select teams:

If you choose to work in teams of your choosing, your group will receive 0 bonus points.

If you choose to work in a team with a partner, you will be randomly matched with another pair of students and your group will receive 20 bonus points.

If you choose to work in a *randomly assigned* team, your group will receive 40 bonus points.

You must make this selection by the end of the second full week of class.

> My team sucks; how can I switch teams?

Life is full of small disappointments. While we would love to spend 12 weeks carefully optimizing groups, that would require a collosal amount of effort that would ultimately not yield anything fruitful. You're stuck.

> My team sucks; how can I punish them for their lack of effort?

On this front, we will be more supportive. While you have to put up with your team regardless of their quality, you can indicate that your team members are not carrying their fair share by issuing a **strike**. This processs works as follows:
1. A team member systematically fails to exert effort on collaborative projects (for example, by not showing up for meetings or not communicating, or by simply leeching off others without contributing.)
2. Your frustration reaches a boiling point. You decide this has to stop. You decide to issue a **strike**
3. You send an email with the following information:
    - `Subject line:` [SSC442] Strike against [Last name of Recipient]
    - `Body:` You do **not** need to provide detailed reasoning. However, you must discuss the actions (plural) you took to remedy the situation before sending the strike email.

A strike is a serious matter, and will reduce that team member's grade on joint work by 10%. If any team-member gets strikes from all other members of his or her team, their grade will be reduced by 50%.

Strikes are *anonymous* so that you do not need to fear social retaliation. However, they are not anonymous to allow you to issue them without thoughtful consideration. Perhaps the other person has a serious issue that is preventing them from completing work (e.g., a relative passing away). Please be thoughtful in using this remedy and consider it a last resort.

> Do I really need to create a team GitHub repository? I don't like GitHub / programming/ work.

Yes, you need to become familiar with GitHub and you and your team will work in a central repository for mini-projects and your final project.

This is for two reasons. First, computer scientists spent a huge amount of time coming up with the solutions that are implemented in GitHub (and other flavors of `git`). Their efforts are largely dedicated toward solving a very concrete goal: how can two people edit the same thing at the same time without creating a ton of new issues. While you could use a paid variant of GitHub (e.g., you could all collaborate over the Microsoft Office suite as implemented by the 360 software that MSU provides), you'd ultimately have the following issues:
1. The software doesn't support some file types.
2. The software doesn't autosave versions.[^1] If someone accidentally deletes something, you're in trouble.
3. You have to learn an entirely new system every time you change classes / universities / jobs, because said institute doesn't buy the product you love.[^2]

[^1]: Some products, of course, solve this problem a little bit. For example, Dropbox allows users to share files with ease (of any file type) and saves a (coarse) version history. However, Dropbox does not allow multiple users to work on the same file, and has no way of merging edits together.

[^2]: This logic is also why we utilize only free software in this course. It sucks to get really good at, say, `SAS` (as I did many years ago) only to realize that the software costs about $10000 and many firms are unwilling to spent that. We will try our best to avoid giving you dead-end skills.

> I'm on a smaller-than-normal team. Does this mean that I have to do more work?

Your instructors are able to count and are aware the teams are imbalanced. Evaluations of final projects will take this into account. While your final product should reflect the best ability of your team, we do not anticipate that the uneven teams will lead to substantively different outputs.



## Suggested outline

You must write and present your analysis as if presenting to a **C-suite executive**. If you are not familiar with this terminology, the C-suite includes, e.g., the CEO, CFO, and COO of a given company. Generally speaking, such executives are not particularly analytically oriented, and therefore your explanations need to be clear, consise (their time is valuable) and contain actionable (or valuable) information.[^6]
    - Concretely, this requires a written memo, which describes the data, analyses, and results. This must be clear and easy to understand for a non-expert in your field. Figures and tables do not apply to the page limit.

Below is a very loose guide to the sort of content that we expect for the final project. Word limits are suggestions only. Note your final report will be approximately

[^6]: This exercise provides you with an opportunity to identify your marketable skills and to practice them. I encourage those who will be looking for jobs soon to take this exercise seriously.

### Introduction

Describe the motivation for this analysis. Briefly describe the dataset, and explain why the analysis you're undertaking matters for society. (Or matters for some decision-making. You should not feel constrained to asking only "big questions." The best projects will be narrow-scope but well-defined.) (**≈300 words**)


### Theory and Background

Provide in-depth background about the data of interest and about your analytics question. (**≈300 words**)

#### "Theory"

Provide some theoretical guidance to the functional relationship you hope to explore. If you're interested on how, say, height affects scoring in the NBA, write down a proposed function that might map height to scoring. Describe how you might look for this unknown relationship in the data.(**≈300 words**)

#### Hypotheses

Make predictions. Declare what you think will happen. (Note, this may carry over from second project.) (**≈250 words**)

### Data and Analyses

#### Data

Given your motivations, limits on feasibility, and hypotheses, describe the data you use. (**≈100 words**)

#### Analyses

Generate the analyses relevant to your hypotheses and interests. Here you must include three figures and must describe what they contain in simple, easy to digest language. Why did you visualize these elements? Your analyses also must include brief discussion.

(**As many words as you need to fully describe your analysis and results**)

### Conclusion

What caveats should we consider? Do you believe this is a truly causal relationship? Why does any of this matter to the decision-maker? (**≈75 words**)
