<!DOCTYPE html>
<html lang="en-us" 
      xmlns:og="http://ogp.me/ns#" 
      xmlns:fb="https://www.facebook.com/2008/fbml">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.8.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Ben Bushong">

  
  
  
    
  
  <meta name="description" content="Preliminaries Code  Load and clean data Legal dual y-axes Combining plots Scatterplot matrices Correlograms Simple regression Coefficient plots Marginal effects plots    Today’s example will pivot between the content from this week and the example below.
We will also use the Ames data again (in addition to the Atlanta weather data). The Ames data is linked below:
  Ames.csv   Preliminaries For this example, we’re again going to use historical weather data from Dark Sky about wind speed and temperature trends for downtown Atlanta (specifically 33.">

  
  <link rel="alternate" hreflang="en-us" href="/example/05-example/">

  


  
  
  
  <meta name="theme-color" content="#18453B">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha256-4w9DunooKSr3MFXHXWyFER38WmPdm361bQS/2KUWZbU=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Fira+Sans+Condensed:400,400i,700,700i%7COverpass:400,400i,700,700i&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  




  


  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="/example/05-example/">

  
  
  
  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@benbushong">
  <meta property="twitter:creator" content="@benbushong">
  
  <meta property="og:site_name" content="Data Analytics">
  <meta property="og:url" content="/example/05-example/">
  <meta property="og:title" content="Introduction to Regression | Data Analytics">
  <meta property="og:description" content="Preliminaries Code  Load and clean data Legal dual y-axes Combining plots Scatterplot matrices Correlograms Simple regression Coefficient plots Marginal effects plots    Today’s example will pivot between the content from this week and the example below.
We will also use the Ames data again (in addition to the Atlanta weather data). The Ames data is linked below:
  Ames.csv   Preliminaries For this example, we’re again going to use historical weather data from Dark Sky about wind speed and temperature trends for downtown Atlanta (specifically 33."><meta property="og:image" content="/img/social-image.png">
  <meta property="twitter:image" content="/img/social-image.png"><meta property="og:locale" content="en-us">
  
    
    <meta property="article:modified_time" content="2020-10-05T16:37:59-04:00">
  

  



  


  


  <link rel="shortcut icon" href="/favicon.ico" />
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/img/apple-touch-icon-57x57.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/img/apple-touch-icon-114x114.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/img/apple-touch-icon-72x72.png" />
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/img/apple-touch-icon-144x144.png" />
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/img/apple-touch-icon-120x120.png" />
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/img/apple-touch-icon-152x152.png" />
  <link rel="icon" type="image/png" href="/img/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="/img/favicon-16x16.png" sizes="16x16" />
  <meta name="application-name" content="SSC 442: Data Analytics" />
  <meta name="msapplication-TileColor" content="#FFFFFF" />
  <meta name="msapplication-TileImage" content="/img/mstile-144x144.png" />


  <title>Introduction to Regression | Data Analytics</title>

</head>


<body id="top" data-spy="scroll" data-offset="70"
    data-target="#TableOfContents"
    >

    <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


    







<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Data Analytics</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Data Analytics</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-end" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/syllabus/"><span>Syllabus</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/schedule/"><span>Schedule</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/content/"><span>Content</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link  active" href="/example/"><span>Examples</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/assignment/"><span>Assignments</span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="https://ssc442.slack.com" target="_blank" rel="noopener"><span><i class="fab fa-slack"></i></span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="https://www.twitch.tv/benbushong" target="_blank" rel="noopener"><span><i class="fab fa-twitch"></i></span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      

      

      

    </ul>

  </div>
</nav>


    

<div class="container-fluid docs">
    <div class="row flex-xl-nowrap">
        <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
            





  
    
  




<form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-3" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>

  
</form>

<nav class="collapse docs-links" id="docs-nav">
  

  
  
  
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/example/">Practical Content</a>

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/example/10-example/">Examples</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/example/10-example/">*10: Classification</a>
      </li>
      
      <li >
        <a href="/example/00-example/">0: Introduction to R</a>
      </li>
      
      <li >
        <a href="/example/01-example/">1: Visualization I</a>
      </li>
      
      <li >
        <a href="/example/02-example/">2: Visualization II</a>
      </li>
      
      <li >
        <a href="/example/03-example/">3: Visualization III</a>
      </li>
      
      <li >
        <a href="/example/04-example/">4: Uncertainty</a>
      </li>
      
      <li class="active">
        <a href="/example/05-example/">5: Linear Regression I</a>
      </li>
      
      <li >
        <a href="/example/06-example/">6: Linear Regression II</a>
      </li>
      
      <li >
        <a href="/example/07-example/">7: Linear Regression III</a>
      </li>
      
      <li >
        <a href="/example/08-example/">8: Nonparametric Regression</a>
      </li>
      
      <li >
        <a href="/example/09-example/">9: Bias vs. Variance</a>
      </li>
      
    </ul>
    

  </div>
  
  
</nav>

        </div>

        

        <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">

            <article class="article">

                <div class="docs-article-container">
                    <h1>Introduction to Regression</h1>

                    

                    

                    

                    <div class="article-style">
                        
<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>

<div id="TOC">
<ul>
<li><a href="#preliminaries">Preliminaries</a></li>
<li><a href="#code">Code</a>
<ul>
<li><a href="#load-and-clean-data">Load and clean data</a></li>
<li><a href="#legal-dual-y-axes">Legal dual y-axes</a></li>
<li><a href="#combining-plots">Combining plots</a></li>
<li><a href="#scatterplot-matrices">Scatterplot matrices</a></li>
<li><a href="#correlograms">Correlograms</a></li>
<li><a href="#simple-regression">Simple regression</a></li>
<li><a href="#coefficient-plots">Coefficient plots</a></li>
<li><a href="#marginal-effects-plots">Marginal effects plots</a></li>
</ul></li>
</ul>
</div>

<div class="fyi">
<p>Today’s example will pivot between the content from this week and the example below.</p>
<p>We will also use the Ames data again (in addition to the Atlanta weather data). The Ames data is linked below:</p>
<ul>
<li><a href="/projects/data/ames.csv"><i class="fas fa-file-csv"></i> <code>Ames.csv</code></a></li>
</ul>
</div>
<div id="preliminaries" class="section level2">
<h2>Preliminaries</h2>
<p>For this example, we’re again going to use historical weather data from <a href="https://darksky.net/forecast/33.7546,-84.39/us12/en">Dark Sky</a> about wind speed and temperature trends for downtown Atlanta (<a href="https://www.google.com/maps/place/33°45&#39;16.4%22N+84°23&#39;24.0%22W/@33.754557,-84.3921977,17z/">specifically <code>33.754557, -84.390009</code></a>) in 2019. We downloaded this data using Dark Sky’s (about-to-be-retired-because-they-were-bought-by-Apple) API using the <a href="https://github.com/hrbrmstr/darksky"><strong>darksky</strong> package</a>.</p>
<p>If you want to follow along with this example, you can download the data below (you’ll likely need to right click and choose “Save Link As…”):</p>
<ul>
<li><a href="/data/atl-weather-2019.csv"><i class="fas fa-file-csv"></i> <code>atl-weather-2019.csv</code></a></li>
</ul>
</div>
<div id="code" class="section level2">
<h2>Code</h2>
<div id="load-and-clean-data" class="section level3">
<h3>Load and clean data</h3>
<p>First, we load the libraries we’ll be using:</p>
<pre class="r"><code>library(tidyverse)  # For ggplot, dplyr, and friends
library(patchwork)  # For combining ggplot plots
library(GGally)     # For scatterplot matrices
library(broom)      # For converting model objects to data frames</code></pre>
<p>Then we load the data with <code>read_csv()</code>. Here we assume that the CSV file lives in a subfolder named <code>data</code>:</p>
<pre class="r"><code>weather_atl &lt;- read_csv(&quot;data/atl-weather-2019.csv&quot;)</code></pre>
</div>
<div id="legal-dual-y-axes" class="section level3">
<h3>Legal dual y-axes</h3>
<p>It is fine (and often helpful) to use two y-axes if the two different scales measure the same thing, like counts and percentages, Fahrenheit and Celsius, pounds and kilograms, inches and centimeters, etc.</p>
<p>To do this, you need to add an argument (<code>sec.axis</code>) to <code>scale_y_continuous()</code> to tell it to use a second axis. This <code>sec.axis</code> argument takes a <code>sec_axis()</code> function that tells ggplot how to transform the scale. You need to specify a formula or function that defines how the original axis gets transformed. This formula uses a special syntax. It needs to start with a <code>~</code>, which indicates that it’s a function, and it needs to use <code>.</code> to stand in for the original value in the original axis.</p>
<p>Since the equation for converting Fahrenheit to Celsius is this…</p>
<p><span class="math display">\[
\text{C} = (32 - \text{F}) \times -\frac{5}{9}
\]</span></p>
<p>…we can specify this with code like so (where <code>.</code> stands for the Fahrenheit value):</p>
<pre class="text"><code>~ (32 - .) * -5 / 9</code></pre>
<p>Here’s a plot of daily high temperatures in Atlanta throughout 2019, with a second axis:</p>
<pre class="r"><code>ggplot(weather_atl, aes(x = time, y = temperatureHigh)) +
  geom_line() +
  scale_y_continuous(sec.axis = sec_axis(trans = ~ (32 - .) * -5/9,
                                         name = &quot;Celsius&quot;)) +
  labs(x = NULL, y = &quot;Fahrenheit&quot;) +
  theme_minimal()</code></pre>
<p><img src="/example/05-example_files/figure-html/atl-weather-dual-axes-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>For fun, we could also convert it to Kelvin, which uses this formula:</p>
<p><span class="math display">\[
\text{K} = (\text{F} - 32) \times \frac{5}{9} + 273.15
\]</span></p>
<pre class="r"><code>ggplot(weather_atl, aes(x = time, y = temperatureHigh)) +
  geom_line() +
  scale_y_continuous(sec.axis = sec_axis(trans = ~ (. - 32) * 5/9 + 273.15,
                                         name = &quot;Kelvin&quot;)) +
  labs(x = NULL, y = &quot;Fahrenheit&quot;) +
  theme_minimal()</code></pre>
<p><img src="/example/05-example_files/figure-html/atl-weather-dual-axes-kelvin-1.png" width="576" style="display: block; margin: auto;" /></p>
</div>
<div id="combining-plots" class="section level3">
<h3>Combining plots</h3>
<p>A good alternative to using two y-axes is to use two plots instead. The <a href="https://github.com/thomasp85/patchwork"><strong>patchwork</strong> package</a> makes this <em>really</em> easy to do with R. There are other similar packages that do this, like <strong>cowplot</strong> and <strong>gridExtra</strong>, but I’ve found that <strong>patchwork</strong> is the easiest to use <em>and</em> it actually aligns the different plot elements like axis lines and legends (yay alignment in CRAP!). The <a href="https://patchwork.data-imaginist.com/articles/guides/assembly.html">documentation for <strong>patchwork</strong></a> is really great and full of examples—you should check it out to see all the things you can do with it!</p>
<p>To use <strong>patchwork</strong>, we need to (1) save our plots as objects and (2) add them together with <code>+</code>.</p>
<p>For instance, is there a relationship between temperature and humidity in Atlanta? We can plot both:</p>
<pre class="r"><code># Temperature in Atlanta
temp_plot &lt;- ggplot(weather_atl, aes(x = time, y = temperatureHigh)) +
  geom_line() +
  geom_smooth() +
  scale_y_continuous(sec.axis = sec_axis(trans = ~ (32 - .) * -5/9,
                                         name = &quot;Celsius&quot;)) +
  labs(x = NULL, y = &quot;Fahrenheit&quot;) +
  theme_minimal()
temp_plot</code></pre>
<p><img src="/example/05-example_files/figure-html/create-temp-humid-plots-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code># Humidity in Atlanta
humidity_plot &lt;- ggplot(weather_atl, aes(x = time, y = humidity)) +
  geom_line() +
  geom_smooth() +
  labs(x = NULL, y = &quot;Humidity&quot;) +
  theme_minimal()
humidity_plot</code></pre>
<p><img src="/example/05-example_files/figure-html/create-temp-humid-plots-2.png" width="576" style="display: block; margin: auto;" /></p>
<p>Right now, these are two separate plots, but we can combine them with <code>+</code> if we load <strong>patchwork</strong>:</p>
<pre class="r"><code>library(patchwork)

temp_plot + humidity_plot</code></pre>
<p><img src="/example/05-example_files/figure-html/patchwork-first-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>By default, <strong>patchwork</strong> will put these side-by-side, but we can change that with the <code>plot_layout()</code> function:</p>
<pre class="r"><code>temp_plot + humidity_plot +
  plot_layout(ncol = 1)</code></pre>
<p><img src="/example/05-example_files/figure-html/patchwork-vertical-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>We can also play with other arguments in <code>plot_layout()</code>. If we want to make the temperature plot taller and shrink the humidity section, we can specify the proportions for the plot heights. Here, the temperature plot is 70% of the height and the humidity plot is 30%:</p>
<pre class="r"><code>temp_plot + humidity_plot +
  plot_layout(ncol = 1, heights = c(0.7, 0.3))</code></pre>
<p><img src="/example/05-example_files/figure-html/patchwork-vertical-resized-1.png" width="576" style="display: block; margin: auto;" /></p>
</div>
<div id="scatterplot-matrices" class="section level3">
<h3>Scatterplot matrices</h3>
<p>We can visualize the correlations between pairs of variables with the <code>ggpairs()</code> function in the <strong>GGally</strong> package. For instance, how correlated are high and low temperatures, humidity, wind speed, and the chance of precipitation? We first make a smaller dataset with just those columns, and then we feed that dataset into <code>ggpairs()</code> to see all the correlation information:</p>
<pre class="r"><code>library(GGally)

weather_correlations &lt;- weather_atl %&gt;%
  select(temperatureHigh, temperatureLow, humidity, windSpeed, precipProbability)

ggpairs(weather_correlations)</code></pre>
<p><img src="/example/05-example_files/figure-html/ggpairs-1.png" width="864" style="display: block; margin: auto;" /></p>
<p>It looks like high and low temperatures are extremely highly positively correlated (r = 0.92). Wind spped and temperature are moderately negatively correlated, with low temperatures having a stronger negative correlation (r = -0.45). There’s no correlation whatsoever between low temperatures and the precipitation probability (r = -0.03) or humidity and high temperatures (r = -0.03).</p>
<p>Even though <code>ggpairs()</code> doesn’t use the standard <code>ggplot(...) + geom_whatever()</code> syntax we’re familiar with, it does behind the scenes, so you can add regular ggplot layers to it:</p>
<pre class="r"><code>ggpairs(weather_correlations) +
  labs(title = &quot;Correlations!&quot;) +
  theme_dark()</code></pre>
<div class="fyi">
<p><strong>TRY IT</strong></p>
<p>Make a ggpairs plot for some of the Ames data.</p>
</div>
</div>
<div id="correlograms" class="section level3">
<h3>Correlograms</h3>
<p>Scatterplot matrices typically include way too much information to be used in actual publications. I use them when doing my own analysis just to see how different variables are related, but I rarely polish them up for public consumption. In the readings for today, Claus Wilke showed a type of plot called a <a href="https://serialmentor.com/dataviz/visualizing-associations.html#associations-correlograms"><em>correlogram</em></a> which <em>is</em> more appropriate for publication.</p>
<p>These are essentially heatmaps of the different correlation coefficients. To make these with ggplot, we need to do a little bit of extra data processing, mostly to reshape data into a long, tidy format that we can plot. Here’s how.</p>
<p>First we need to build a correlation matrix of the main variables we care about. Ordinarily the <code>cor()</code> function in R takes two arguments—x and y—and it will return a single correlation value. If you feed a data frame into <code>cor()</code> though, it’ll calculate the correlation between each pair of columns</p>
<pre class="r"><code># Create a correlation matrix
things_to_correlate &lt;- weather_atl %&gt;%
  select(temperatureHigh, temperatureLow, humidity, windSpeed, precipProbability) %&gt;%
  cor()

things_to_correlate</code></pre>
<pre><code>##                   temperatureHigh temperatureLow humidity windSpeed precipProbability
## temperatureHigh              1.00          0.920   -0.030    -0.377            -0.124
## temperatureLow               0.92          1.000    0.112    -0.450            -0.026
## humidity                    -0.03          0.112    1.000     0.011             0.722
## windSpeed                   -0.38         -0.450    0.011     1.000             0.196
## precipProbability           -0.12         -0.026    0.722     0.196             1.000</code></pre>
<p>The two halves of this matrix (split along the diagonal line) are identical, so we can remove the lower triangle with this code (which will set all the cells in the lower triangle to <code>NA</code>):</p>
<pre class="r"><code># Get rid of the lower triangle
things_to_correlate[lower.tri(things_to_correlate)] &lt;- NA
things_to_correlate</code></pre>
<pre><code>##                   temperatureHigh temperatureLow humidity windSpeed precipProbability
## temperatureHigh                 1           0.92    -0.03    -0.377            -0.124
## temperatureLow                 NA           1.00     0.11    -0.450            -0.026
## humidity                       NA             NA     1.00     0.011             0.722
## windSpeed                      NA             NA       NA     1.000             0.196
## precipProbability              NA             NA       NA        NA             1.000</code></pre>
<p>Finally, in order to plot this, the data needs to be in tidy (or long) format. Here we convert the <code>things_to_correlate</code> matrix into a data frame, add a column for the row names, take all the columns and put them into a single column named <code>measure1</code>, and take all the correlation numbers and put them in a column named <code>cor</code> In the end, we make sure the measure variables are ordered by their order of appearance (otherwise they plot alphabetically and don’t make a triangle)</p>
<pre class="r"><code>things_to_correlate_long &lt;- things_to_correlate %&gt;%
  # Convert from a matrix to a data frame
  as.data.frame() %&gt;%
  # Matrixes have column names that don&#39;t get converted to columns when using
  # as.data.frame(), so this adds those names as a column
  rownames_to_column(&quot;measure2&quot;) %&gt;%
  # Make this long. Take all the columns except measure2 and put their names in
  # a column named measure1 and their values in a column named cor
  pivot_longer(cols = -measure2,
               names_to = &quot;measure1&quot;,
               values_to = &quot;cor&quot;) %&gt;%
  # Make a new column with the rounded version of the correlation value
  mutate(nice_cor = round(cor, 2)) %&gt;%
  # Remove rows where the two measures are the same (like the correlation
  # between humidity and humidity)
  filter(measure2 != measure1) %&gt;%
  # Get rid of the empty triangle
  filter(!is.na(cor)) %&gt;%
  # Put these categories in order
  mutate(measure1 = fct_inorder(measure1),
         measure2 = fct_inorder(measure2))

things_to_correlate_long</code></pre>
<pre><code>## # A tibble: 10 x 4
##    measure2        measure1              cor nice_cor
##    &lt;fct&gt;           &lt;fct&gt;               &lt;dbl&gt;    &lt;dbl&gt;
##  1 temperatureHigh temperatureLow     0.920      0.92
##  2 temperatureHigh humidity          -0.0301    -0.03
##  3 temperatureHigh windSpeed         -0.377     -0.38
##  4 temperatureHigh precipProbability -0.124     -0.12
##  5 temperatureLow  humidity           0.112      0.11
##  6 temperatureLow  windSpeed         -0.450     -0.45
##  7 temperatureLow  precipProbability -0.0255    -0.03
##  8 humidity        windSpeed          0.0108     0.01
##  9 humidity        precipProbability  0.722      0.72
## 10 windSpeed       precipProbability  0.196      0.2</code></pre>
<p>Phew. With the data all tidied like that, we can make a correlogram with a heatmap. We have manipulated the fill scale a little so that it’s diverging with three colors: a high value, a midpoint value, and a low value.</p>
<pre class="r"><code>ggplot(things_to_correlate_long,
       aes(x = measure2, y = measure1, fill = cor)) +
  geom_tile() +
  geom_text(aes(label = nice_cor)) +
  scale_fill_gradient2(low = &quot;#E16462&quot;, mid = &quot;white&quot;, high = &quot;#0D0887&quot;,
                       limits = c(-1, 1)) +
  labs(x = NULL, y = NULL) +
  coord_equal() +
  theme_minimal() +
  theme(panel.grid = element_blank())</code></pre>
<p><img src="/example/05-example_files/figure-html/cor-heatmap-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>Instead of using a heatmap, we can also use points, which encode the correlation information both as color <em>and</em> as size. To do that, we just need to switch <code>geom_tile()</code> to <code>geom_point()</code> and set the <code>size = cor</code> mapping:</p>
<pre class="r"><code>ggplot(things_to_correlate_long,
       aes(x = measure2, y = measure1, color = cor)) +
  # Size by the absolute value so that -0.7 and 0.7 are the same size
  geom_point(aes(size = abs(cor))) +
  scale_color_gradient2(low = &quot;#E16462&quot;, mid = &quot;white&quot;, high = &quot;#0D0887&quot;,
                        limits = c(-1, 1)) +
  scale_size_area(max_size = 15, limits = c(-1, 1), guide = FALSE) +
  labs(x = NULL, y = NULL) +
  coord_equal() +
  theme_minimal() +
  theme(panel.grid = element_blank())</code></pre>
<p><img src="/example/05-example_files/figure-html/cor-points-1.png" width="480" style="display: block; margin: auto;" /></p>
</div>
<div id="simple-regression" class="section level3">
<h3>Simple regression</h3>
<p>We finally get to this week’s content. Although correlation is nice, we eventually may want to visualize regression. The lecture has shown us some very intuitive, straightforward ways to think about regression (aka, a line). Simple regression is easy to visualize, since you’re only working with an <span class="math inline">\(X\)</span> and a <span class="math inline">\(Y\)</span>. For instance, what’s the relationship between humidity and high temperatures during the summer?</p>
<p>First, let’s filter the data to only look at the summer. We also add a column to scale up the humidity value—right now it’s on a scale of 0-1 (for percentages), but when interpreting regression we talk about increases in whole units, so we’d talk about moving from 0% humidity to 100% humidity, which isn’t helpful, so instead we multiply everything by 100 so we can talk about moving from 50% humidity to 51% humidity. We also scale up a couple other variables that we’ll use in the larger model later.</p>
<pre class="r"><code>weather_atl_summer &lt;- weather_atl %&gt;%
  filter(time &gt;= &quot;2019-05-01&quot;, time &lt;= &quot;2019-09-30&quot;) %&gt;%
  mutate(humidity_scaled = humidity * 100,
         moonPhase_scaled = moonPhase * 100,
         precipProbability_scaled = precipProbability * 100,
         cloudCover_scaled = cloudCover * 100)</code></pre>
<p>Then we can build a simple regression model:</p>
<pre class="r"><code>model_simple &lt;- lm(temperatureHigh ~ humidity_scaled,
                   data = weather_atl_summer)

tidy(model_simple, conf.int = TRUE)</code></pre>
<pre><code>## # A tibble: 2 x 7
##   term            estimate std.error statistic  p.value conf.low conf.high
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)      104.       2.35       44.3  1.88e-88   99.5     109.   
## 2 humidity_scaled   -0.241    0.0358     -6.74 3.21e-10   -0.312    -0.170</code></pre>
<p>We can interpret these coefficients like so:</p>
<ul>
<li>The intercept shows that the average temperature when there’s 0% humidity is 104°. There are no days with 0% humidity though, so we can ignore the intercept—it’s really just here so that we can draw the line.</li>
<li>The coefficient for <code>humidity_scaled</code> shows that a one percent increase in humidity is associated with a 0.241° decrease in temperature, on average.</li>
</ul>
<p>Visualizing this model is simple, since there are only two variables:</p>
<pre class="r"><code>ggplot(weather_atl_summer,
       aes(x = humidity_scaled, y = temperatureHigh)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/example/05-example_files/figure-html/plot-simple-model-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>And indeed, as humidity increases, temperatures decrease.</p>
</div>
<div id="coefficient-plots" class="section level3">
<h3>Coefficient plots</h3>
<p>But if we use multiple variables in the model (and we will do this a lot going forward), it gets really hard to visualize the results since we’re working with multiple dimensions. Instead, we can use coefficient plots to see the individual coefficients in the model.</p>
<p>First, let’s build a more complex model:</p>
<pre class="r"><code>model_complex &lt;- lm(temperatureHigh ~ humidity_scaled + moonPhase_scaled +
                      precipProbability_scaled + windSpeed + pressure + cloudCover_scaled,
                    data = weather_atl_summer)
tidy(model_complex, conf.int = TRUE)</code></pre>
<pre><code>## # A tibble: 7 x 7
##   term                     estimate std.error statistic   p.value conf.low conf.high
##   &lt;chr&gt;                       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)              262.      125.         2.09  0.0380    14.8      510.    
## 2 humidity_scaled           -0.111     0.0757    -1.47  0.143     -0.261      0.0381
## 3 moonPhase_scaled           0.0116    0.0126     0.917 0.360     -0.0134     0.0366
## 4 precipProbability_scaled   0.0356    0.0203     1.75  0.0820    -0.00458    0.0758
## 5 windSpeed                 -1.78      0.414     -4.29  0.0000326 -2.59      -0.958 
## 6 pressure                  -0.157     0.122     -1.28  0.203     -0.398      0.0854
## 7 cloudCover_scaled         -0.0952    0.0304    -3.14  0.00207   -0.155     -0.0352</code></pre>
<p>We can interpret these coefficients like so:</p>
<ul>
<li>Holding everything else constant, a 1% increase in humidity is associated with a 0.11° decrease in the high temperature, on average, but the effect is not statistically significant</li>
<li>Holding everything else constant, a 1% increase in moon visibility is associated with a 0.01° increase in the high temperature, on average, and the effect is not statistically significant</li>
<li>Holding everything else constant, a 1% increase in the probability of precipitation is associated with a 0.04° increase in the high temperature, on average, and the effect is not statistically significant</li>
<li>Holding everything else constant, a 1 mph increase in the wind speed is associated with a 1.8° decrease in the high temperature, on average, and the effect <em>is</em> statistically significant</li>
<li>Holding everything else constant, a 1 unit increase in barometric pressure is associated with a 0.15° decrease in the high temperature, on average, and the effect is not statistically significant</li>
<li>Holding everything else constant, a 1% increase in cloud cover is associated with a 0.01° decrease in the high temperature, on average, and the effect <em>is</em> statistically significant</li>
<li>The intercept is pretty useless. It shows that the predicted temperature will be 262° when humidity is 0%, the moon is invisible, there’s no chance of precipitation, no wind, no barometric pressure, and no cloud cover. Yikes.</li>
</ul>
<p>To plot all these things at once, we’ll store the results of <code>tidy(model_complex)</code> as a data frame, remove the useless intercept, and plot it using <code>geom_pointrange()</code>:</p>
<pre class="r"><code>model_tidied &lt;- tidy(model_complex, conf.int = TRUE) %&gt;%
  filter(term != &quot;(Intercept)&quot;)

ggplot(model_tidied,
       aes(x = estimate, y = term)) +
  geom_vline(xintercept = 0, color = &quot;red&quot;, linetype = &quot;dotted&quot;) +
  geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +
  labs(x = &quot;Coefficient estimate&quot;, y = NULL) +
  theme_minimal()</code></pre>
<p><img src="/example/05-example_files/figure-html/coef-plot-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Neat! Now we can see how big these different coefficients are and how close they are to zero. Wind speed has a big significant effect on temperature. The others are all very close to zero.</p>
</div>
<div id="marginal-effects-plots" class="section level3">
<h3>Marginal effects plots</h3>
<p>Instead of just looking at the coefficients, we can also see the effect of moving different variables up and down like sliders and switches. Remember that regression coefficients allow us to build actual mathematical formulas that predict the value of Y. The coefficients from <code>model_compex</code> yield the following big hairy ugly equation:</p>
<p><span class="math display">\[
\begin{aligned}
\hat{\text{High temperature}} =&amp; 262 - 0.11 \times \text{humidity_scaled } \\
&amp; + 0.01 \times \text{moonPhase_scaled } + 0.04 \times \text{precipProbability_scaled } \\
&amp; - 1.78 \times \text{windSpeed} - 0.16 \times \text{pressure} - 0.095 \times \text{cloudCover_scaled}
\end{aligned}
\]</span></p>
<p>If we plug in values for each of the explanatory variables, we can get the predicted value of high temperature, or <span class="math inline">\(\hat{y}\)</span>.</p>
<p>The <code>augment()</code> function in the <strong>broom</strong> library allows us to take a data frame of explanatory variable values, plug them into the model equation, and get predictions out. For example, let’s set each of the variables to some arbitrary values (50% for humidity, moon phase, chance of rain, and cloud cover; 1000 for pressure, and 1 MPH for wind speed).</p>
<pre class="r"><code>newdata_example &lt;- tibble(humidity_scaled = 50, moonPhase_scaled = 50,
                          precipProbability_scaled = 50, windSpeed = 1,
                          pressure = 1000, cloudCover_scaled = 50)
newdata_example</code></pre>
<pre><code>## # A tibble: 1 x 6
##   humidity_scaled moonPhase_scaled precipProbability_scaled windSpeed pressure cloudCover_scaled
##             &lt;dbl&gt;            &lt;dbl&gt;                    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;             &lt;dbl&gt;
## 1              50               50                       50         1     1000                50</code></pre>
<p>We can plug these values into the model with <code>augment()</code>:</p>
<pre class="r"><code># I use select() here because augment() returns columns for all the explanatory
# variables, and the .fitted column with the predicted value is on the far right
# and gets cut off
augment(model_complex, newdata = newdata_example, se_fit=TRUE) %&gt;%
  select(.fitted, .se.fit)</code></pre>
<p>Given these weather conditions, the predicted high temperature is 96.2°. Now you’re an armchair meteorologist!</p>
<p>We can follow the same pattern to show how the predicted temperature changes as specific variables change across a whole range. Here, we create a data frame of possible wind speeds and keep all the other explanatory variables at their means:</p>
<pre class="r"><code>newdata &lt;- tibble(windSpeed = seq(0, 8, 0.5),
                  pressure = mean(weather_atl_summer$pressure),
                  precipProbability_scaled = mean(weather_atl_summer$precipProbability_scaled),
                  moonPhase_scaled = mean(weather_atl_summer$moonPhase_scaled),
                  humidity_scaled = mean(weather_atl_summer$humidity_scaled),
                  cloudCover_scaled = mean(weather_atl_summer$cloudCover_scaled))
newdata</code></pre>
<pre><code>## # A tibble: 17 x 6
##    windSpeed pressure precipProbability_scaled moonPhase_scaled humidity_scaled cloudCover_scaled
##        &lt;dbl&gt;    &lt;dbl&gt;                    &lt;dbl&gt;            &lt;dbl&gt;           &lt;dbl&gt;             &lt;dbl&gt;
##  1       0      1016.                     40.2             50.7            64.8              29.5
##  2       0.5    1016.                     40.2             50.7            64.8              29.5
##  3       1      1016.                     40.2             50.7            64.8              29.5
##  4       1.5    1016.                     40.2             50.7            64.8              29.5
##  5       2      1016.                     40.2             50.7            64.8              29.5
##  6       2.5    1016.                     40.2             50.7            64.8              29.5
##  7       3      1016.                     40.2             50.7            64.8              29.5
##  8       3.5    1016.                     40.2             50.7            64.8              29.5
##  9       4      1016.                     40.2             50.7            64.8              29.5
## 10       4.5    1016.                     40.2             50.7            64.8              29.5
## 11       5      1016.                     40.2             50.7            64.8              29.5
## 12       5.5    1016.                     40.2             50.7            64.8              29.5
## 13       6      1016.                     40.2             50.7            64.8              29.5
## 14       6.5    1016.                     40.2             50.7            64.8              29.5
## 15       7      1016.                     40.2             50.7            64.8              29.5
## 16       7.5    1016.                     40.2             50.7            64.8              29.5
## 17       8      1016.                     40.2             50.7            64.8              29.5</code></pre>
<p>If we feed this big data frame into <code>augment()</code>, we can get the predicted high temperature for each row. We can also use the <code>.se.fit</code> column to calculate the 95% confidence interval for each predicted value. We take the standard error, multiply it by -1.96 and 1.96 (or the quantile of the normal distribution at 2.5% and 97.5%), and add that value to the estimate.</p>
<pre class="r"><code>predicted_values &lt;- augment(model_complex, newdata = newdata, se_fit=TRUE) %&gt;%
  mutate(conf.low = .fitted + (-1.96 * .se.fit),
         conf.high = .fitted + (1.96 * .se.fit))

predicted_values %&gt;%
  select(windSpeed, .fitted, .se.fit, conf.low, conf.high) %&gt;%
  head()</code></pre>
<pre><code>## # A tibble: 6 x 5
##   windSpeed .fitted .se.fit conf.low conf.high
##       &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1       0      95.3   1.63      92.2      98.5
## 2       0.5    94.5   1.42      91.7      97.2
## 3       1      93.6   1.22      91.2      96.0
## 4       1.5    92.7   1.03      90.7      94.7
## 5       2      91.8   0.836     90.1      93.4
## 6       2.5    90.9   0.653     89.6      92.2</code></pre>
<p>Cool! Just looking at the data in the table, we can see that predicted temperature drops as windspeed increases. We can plot this to visualize the effect:</p>
<pre class="r"><code>ggplot(predicted_values, aes(x = windSpeed, y = .fitted)) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high),
              fill = &quot;#BF3984&quot;, alpha = 0.5) +
  geom_line(size = 1, color = &quot;#BF3984&quot;) +
  labs(x = &quot;Wind speed (MPH)&quot;, y = &quot;Predicted high temperature (F)&quot;) +
  theme_minimal()</code></pre>
<p><img src="/example/05-example_files/figure-html/mfx-plot-simple-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>We just manipulated one of the model coefficients and held everything else at its mean. We can manipulate multiple variables too and encode them all on the graph. For instance, what is the effect of windspeed <em>and</em> cloud cover on the temperature?</p>
<p>We’ll follow the same process, but vary both <code>windSpeed</code> and <code>cloudCover_scaled</code>. Instead of using <code>tibble()</code>, we use <code>exapnd_grid()</code>, which creates every combination of the variables we specify. Instead of varying cloud cover by every possible value (like from 0 to 100), we’ll choose four possible cloud cover types: 0%, 33%, 66%, and 100%. Everything else will be at its mean.</p>
<pre class="r"><code>newdata_fancy &lt;- expand_grid(windSpeed = seq(0, 8, 0.5),
                             pressure = mean(weather_atl_summer$pressure),
                             precipProbability_scaled = mean(weather_atl_summer$precipProbability_scaled),
                             moonPhase_scaled = mean(weather_atl_summer$moonPhase_scaled),
                             humidity_scaled = mean(weather_atl_summer$humidity_scaled),
                             cloudCover_scaled = c(0, 33, 66, 100))
newdata_fancy</code></pre>
<pre><code>## # A tibble: 68 x 6
##    windSpeed pressure precipProbability_scaled moonPhase_scaled humidity_scaled cloudCover_scaled
##        &lt;dbl&gt;    &lt;dbl&gt;                    &lt;dbl&gt;            &lt;dbl&gt;           &lt;dbl&gt;             &lt;dbl&gt;
##  1       0      1016.                     40.2             50.7            64.8                 0
##  2       0      1016.                     40.2             50.7            64.8                33
##  3       0      1016.                     40.2             50.7            64.8                66
##  4       0      1016.                     40.2             50.7            64.8               100
##  5       0.5    1016.                     40.2             50.7            64.8                 0
##  6       0.5    1016.                     40.2             50.7            64.8                33
##  7       0.5    1016.                     40.2             50.7            64.8                66
##  8       0.5    1016.                     40.2             50.7            64.8               100
##  9       1      1016.                     40.2             50.7            64.8                 0
## 10       1      1016.                     40.2             50.7            64.8                33
## # … with 58 more rows</code></pre>
<p>Notice now that <code>windSpeed</code> repeats four times (0, 0, 0, 0, 0.5, 0.5, etc.), since there are four possible <code>cloudCover_scaled</code> values (0, 33, 66, 100).</p>
<p>We can plot this now, just like before, with wind speed on the x-axis, the predicted temperature on the y-axis, and colored and faceted by cloud cover:</p>
<pre class="r"><code>predicted_values_fancy &lt;- augment(model_complex, newdata = newdata_fancy, se_fit=TRUE) %&gt;%
  mutate(conf.low = .fitted + (-1.96 * .se.fit),
         conf.high = .fitted + (1.96 * .se.fit)) %&gt;%
  # Make cloud cover a categorical variable
  mutate(cloudCover_scaled = factor(cloudCover_scaled))

ggplot(predicted_values_fancy, aes(x = windSpeed, y = .fitted)) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = cloudCover_scaled),
              alpha = 0.5) +
  geom_line(aes(color = cloudCover_scaled), size = 1) +
  labs(x = &quot;Wind speed (MPH)&quot;, y = &quot;Predicted high temperature (F)&quot;) +
  theme_minimal() +
  guides(fill = FALSE, color = FALSE) +
  facet_wrap(vars(cloudCover_scaled), nrow = 1)</code></pre>
<p><img src="/example/05-example_files/figure-html/mfx-complex-1.png" width="864" style="display: block; margin: auto;" /></p>
<p>Nice. Temperatures go down slightly as cloud cover increases. If we wanted to improve the model, we’d add an interaction term between cloud cover and windspeed so that each line would have a different slope in addition to a different intercept, but that’s beyond the scope of this class.</p>
</div>
</div>

                    </div>

                    



                    
                </div>

                <div class="body-footer">
                    <p>Last updated on October 5, 2020</p>

                    


                    

                </div>

            </article>

            <footer>
    <hr>

    <div class="row course-info">
        <div class="col-md-7">
            <p>
                <strong>SSC 442: Data Analytics (Fall Semester 2020)</strong><br>

                <a href="https://www.msu.edu" target="_blank" rel="noopener">Michigan State University</a> &emsp;&emsp;
                <a href="https://socialscience.msu.edu/" target="_blank" rel="noopener">College of Social Science</a>
            </p>

            <p>
                <a href="https://www.benbushong.com" target="_blank" rel="noopener"><i class="fas fa-user"></i>
                    Prof. Ben Bushong</a> &emsp;&emsp;
                <a href="mailto:bbushong@msu.edu"><i class="fas fa-envelope"></i>
                    bbushong@msu.edu</a>
            </p>

            <p>
                <i class="far fa-calendar-alt"></i> Tuesday and Thursday &emsp;&emsp;
                <i class="far fa-clock"></i> 10:20 - 11:40 AM 
                
            </p>
        </div>

        <div class="col-md-5 credits">
            <p>All content licensed under a <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.</p>
            
            <p>Content <i class="fab fa-creative-commons"></i> 2020 <a href="https://www.benbushong.com" target="_blank" rel="noopener">Ben Bushong</a></p>
        
            <p>This site created with the <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> in <a href="https://bookdown.org/yihui/blogdown/" target="_blank" rel="noopener">blogdown</a> and <a href="https://gohugo.io/" target="_blank" rel="noopener">Hugo</a>. </p>
            
            <p><a href="https://github.com/" target="_blank" rel="noopener"><i class="fab fa-github"></i> View the source at GitHub.</a></p>
        </div>
    </div>
</footer>


        </main>
    </div>
</div>

        

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js" integrity="sha256-eOgo0OtLL4cdq7RdwRUiGKLX9XsIJ7nGhWEKbohmVAQ=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/r.min.js"></script>
        
      

    

    
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    <script>const isSiteThemeDark = false;</script>
    

    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.1/anchor.min.js" integrity="sha256-pB/deHc9CGfFpJRjC43imB29Rse8tak+5eXqntO94ck=" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    

    
    

    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
    
    
    
    <script src="/js/academic.min.6f7ce8be710290b8c431bbc97f405d15.js"></script>

    



    
    

    
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
